
import { scps } from './Data';
import { useParams } from 'react-router';
// above code is used to use a URL path generated by the react router as a value
export default function ScpDetail()
{
    // Set the props based on the scp item
    const {item} = useParams(); // get the item from the URL path
    // find the scp that matches the item
    const scp = scps.find(s => s.item === item)

    return (
        <div className="container">
            <h1><b>Item #: </b>{scp.item}</h1>
            <h2 className="alert alert-danger"><b>Object Class: </b>
                <span style={{color: scp.objectClass === 'Safe' ? 'green' : 'darkred'}}>{scp.objectClass}</span></h2>
            <p className="text-center">
                <img
                    src={scp.image}
                    alt={scp.item}
                    style={scp.item === 'SCP-005' ? { width: '550px', maxWidth: '100%', height: 'auto' } : { maxWidth: '100%', height: 'auto' }}
                />
            </p>
            <h3 className="special-heading">Special Containment Procedures:</h3>
            <p>{scp.procedures}</p>
            <h3 className="special-heading">Description:</h3>
            <p>{scp.description}</p>
        </div>
    )
}
